# Generated by Django 6.0.3 on 2026-03-26 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.IntegerField()),
                ('date', models.IntegerField()),
                ('name', models.CharField()),
                ('videoPhoto', models.URLField()),
                ('description', models.TextField()),
                ('credit', models.CharField()),
            ],
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
