# Generated by Django 6.0.3 on 2026-03-27 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0002_info_delete_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField()),
                ('title', models.CharField()),
                ('description', models.TextField()),
                ('media_url',  models.URLField()),
            ],
        ),
    ]
