# Generated by Django 6.0.3 on 2026-03-28 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0003_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='date',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField()),
                ('title', models.CharField()),
                ('description', models.TextField()),
                ('media_url', models.URLField()),
            ],
        ),
    ]
